codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: 90%    # Based on your testing standards requirement
        threshold: 1%  # Allow a small decrease without failing
    patch:
      default:
        target: 90%
        threshold: 1%

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - packages/*/src

ignore:
  - "packages/**/dist"
  - "packages/**/__tests__"
  - "packages/**/__mocks__"
  - "packages/**/jest.config.ts" 